### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by objcoding** [objcoding/objcoding.github.io#1]
觉得有什么疑问的，可以在文章下面评论哦～

**Comment by Chankin026** [comment]
你的博客经常性进不去

**Comment by objcoding** [comment]
> 你的博客经常性进不去

由于github pages服务器在国外，所以如果没有翻墙，应该会慢点的，我翻墙打开都是秒进的。

**Comment by Chankin026** [comment]
> > 你的博客经常性进不去
> 
> 由于github pages服务器在国外，所以如果没有翻墙，应该会慢点的，我翻墙打开都是秒进的。

了解了
